time-zone = "Asia/Yekaterinburg"

[fields]
hide = ["*", "!record.extra", "!exception"]

[fields.predefined]
time.names = ["record.time.timestamp", "@timestamp"]
message.names = ["record.message", "message", "log"]
caller.names = ["record.function"]
caller-file.names = ["record.file.path"]
caller-line.names = ["record.line"]
logger.names = []

[[fields.predefined.level.variants]]
names = [ "record.level.name" ]

[fields.predefined.level.variants.values]
error = ["error", "err", "fatal", "critical", "panic"]
warning = ["warning", "warn"]
info = ["info", "information"]
debug = ["debug"]
trace = ["trace"]
